appinfo/app.php, appinfo/info.xml
requires owncloud/core#12555 to be merged, will make this app require oc8
=> make search results app specific

appinfo/info.xml
@DeepDiver1975
owncloud/core#13706
=> Remove isShipped

controller/lib/bookmarks.php
Tried to fix the issue I reported some time ago: https://github.com/owncloud/bookmarks/issues/121
Hope it's ok like that.
=> remove fixed “oc_”-prefix.

controller/lib/bookmarks.php
remove fixed “oc_”-prefix.
more ticks
=> Backport of #129 to stable8

lib/bookmarks.php
=> backport database fix from c30d34c to stable7

appinfo/info.xml
=> Fix OCS ID for stable8

controller/webviewcontroller.php, js/bookmarklet.js, templates/addBookmarklet.php
Fixes #127 and supersedes #132 
Like to test or review? @TtuxX @jonmach @Chouchen @jeka @buzzra @mbressman @utahbmxer @raimerik @tflidd @shaneonabike @dnaber-de
=> [bookmarklet] Reintroduce tags and fix editing existing entries

controller/webviewcontroller.php, js/bookmarklet.js, templates/addBookmarklet.php
Adding tags in bookmarklet, fix #127
Update for existing bookmark : now gets existing associated tags, fix #127
add tagit
fix updating of bookmarks via bookmarklet
=> Backport of #173 (Reintroduce tags and fix editing existing entries)

controller/webviewcontroller.php
Fixes https://github.com/owncloud/bookmarks/issues/180
=> Allow iframes

appinfo/app.php
backport of https://github.com/owncloud/bookmarks/pull/198
=> [backport][stable8.2] Do not load routes when not needed

appinfo/app.php
=> [backport] [stable8.1] Do not load routes when not needed

js/bookmarklet.js
Backport of https://github.com/owncloud/bookmarks/pull/179
=> [backport] [stable8.2] autoclosing bookmarklet

js/bookmarklet.js
=> [backport] [stable8.1] autoclosing bookmarklet

appinfo/info.xml
=> Only specify one owncloud version requirement

appinfo/info.xml
Backport of https://github.com/owncloud/bookmarks/pull/174
=> [stable8.2] Fix OCS id

appinfo/app.php
@MorrisJobke @LukasReschke @rullzer @blizzz
=> Better navigation entry

controller/lib/bookmarks.php
Fix the DELETE and UPDATE tag statements and parameters.
=> renameTag SQL bugfix

controller/lib/bookmarks.php, tests/lib_bookmark_test.php
=> Improve encoding detection

controller/lib/bookmarks.php, tests/lib_bookmark_test.php
Improve encoding detection
adjust unit test
=> [9.0] Backport of #246

controller/lib/bookmarks.php, tests/lib_bookmark_test.php
Improve encoding detection
adjust unit test
=> [8.2] Backport of #246

controller/lib/bookmarks.php, tests/lib_bookmark_test.php
Improve encoding detection
adjust unit test
=> [8.1] backport of #246

controller/lib/bookmarks.php
=> Fix overwrite of bookmarks when importing links without URL

controller/lib/bookmarks.php, controller/rest/publiccontroller.php, controller/rest/tagscontroller.php, controller/webviewcontroller.php
=> Cleanup controllers

css/3rdparty/jquery.tagit.css, css/bookmarks.css, js/3rdparty/tag-it.js
Make tag filter bar visible
Full width tag filter bar
Ensure the tag filter bar is as large as the one for adding bookmarks
Tags under filter search bar
Ensure the selected tags appear below the tags filter search bar.
Update bookmarks.css
=> Backport of #261 to stable9.1

css/3rdparty/jquery.tagit.css, css/bookmarks.css, js/3rdparty/tag-it.js
Make tag filter bar visible
Full width tag filter bar
Ensure the tag filter bar is as large as the one for adding bookmarks
Tags under filter search bar
Ensure the selected tags appear below the tags filter search bar.
Update bookmarks.css
=> Backport of #261 to stable9

css/3rdparty/jquery.tagit.css, css/bookmarks.css, js/3rdparty/tag-it.js
Make tag filter bar visible
Full width tag filter bar
Ensure the tag filter bar is as large as the one for adding bookmarks
Tags under filter search bar
Ensure the selected tags appear below the tags filter search bar.
Update bookmarks.css
=> Backport of #261 to stable8.2

.travis.yml, appinfo/info.xml
let's see whether the travis changes are ok :D
=> master branch to be now release branch for any Nc/OC version starting 9.0

appinfo/info.xml
Otherwise coming Nextcloud appstore refuses to accept it.
=> remove deprecated standalone element

appinfo/application.php
Fix for https://github.com/owncloud/bookmarks/issues/289
=> avoid 500 when accessing bookmarks while being logged out, fixes #289

controller/lib/search.php, templates/main.php
cc @blizzz
See https://github.com/nextcloud/server/pull/1948
=> Move away from legacy OC_L10N

appinfo/application.php, controller/lib/bookmarks.php, controller/lib/search.php, controller/rest/bookmarkcontroller.php, controller/rest/publiccontroller.php, controller/rest/tagscontroller.php, controller/webviewcontroller.php, tests/TestCase.php, tests/bootstrap.php, tests/lib_bookmark_test.php, tests/publiccontroller_test.php
=> Make Bookmarks class non-static

controller/lib/bookmarks.php, tests/lib_bookmark_test.php
=> don't give up on a cURL 18 error

templates/main.php
=> Change out "Add to ownCloud" for "Add to Nextcloud"

.travis.yml
we run into time outs of fetching that tool. And we really do not need to run it that often.
=> do not run coverage tests every time

templates/settings.php
Kudos to  @LukasReschke 💟 
@eppfel this should fix it.
=> encode requesttoken in url,  fixes #319

.travis.yml, appinfo/application.php, appinfo/info.xml, controller/lib/bookmarks.php, controller/rest/bookmarkcontroller.php, tests/lib_bookmark_test.php, tests/publiccontroller_test.php
=> add Nextcloud 12 compatibility and PHP 7.1 tests

appinfo/application.php, appinfo/routes.php, controller/rest/publiccontroller.php, tests/publiccontroller_test.php
Hi,
after my frustrations with the current API (while working on https://github.com/marcelklehr/floccus) I decided to extend the public API with full CRUD support. The methods are mostly copied from the Bookmark controller, as the framework is new to me, so please excuse any bugs :)
=> Add CRUD methods to public REST API

appinfo/info.xml
I guess the syntax is OK, but I couldn't test as the appstore doesn't allow just info.xml validation.
=> add screenshots to info.xml

tests/lib_bookmark_test.php
As per  #305 this test is expected to fail on mysql and pgsql atm. ~~Please hold off merging until #332 is merged, which should fix this.~~ This should probably be merged before #332, so we can verify just that ;)
=> Test renameTag

.travis.yml, appinfo/info.xml
=> Adjust tests for phpunit

controller/lib/bookmarks.php, tests/lib_bookmark_test.php
This is a work in progress, I've added you as a collaborator so you can also push to the branch @blizzz ;)
This will hopefully also fix #305
=> Use query builder

README.md
should be item[tags][] instead of item[]
FIxes #353
=> README: Fix API docs: tags param was wrong

controller/lib/bookmarks.php, tests/lib_bookmark_test.php
not just the first one :)
fixes #357
=> Fix lib#findUniqueBookmark: Return all tags

controller/lib/bookmarks.php, tests/lib_bookmark_test.php
=> Fix delete tag

controller/lib/bookmarks.php
duplicates handling handled one duplicate only
=> Fix rename tag

appinfo/application.php
=> Fix v1 API: Re-add PublicController to container

controller/rest/bookmarkcontroller.php, js/bookmarks.js, tests/bookmarkcontroller_test.php
This is preliminary. I'm not sure it'll work. Especially whether it allows for actually removing/resetting attribs.
Fixes #359
=> API: Allow omitting params in editBookmark

README.md
Added small formatting changes.
=> Small formatting changes

controller/rest/internalbookmarkcontroller.php
=> Fix internalBookmarksController#import

controller/lib/bookmarks.php, tests/lib_bookmark_test.php
Fixed the exception thrown in #366
=> Fix findTags: Use query param to inject tags

appinfo/application.php
=> Fix Nullpointer exception if user is not logged in

controller/rest/bookmarkcontroller.php, tests/bookmarkcontroller_test.php, tests/lib_bookmark_test.php
=> fix: clickBookmark's DB query was not migrated

README.md
Add theScrabi/NCBookmarks to compainion apps
=> Add theScrabi/NCBookmarks to compainion apps
